// Lead-delivery sinks: Netlify (forwards into the existing starter-project
// Netlify Form so the CRM/notification wiring already built for the web
// intake form fires for phone leads too), Telegram (instant human ping),
// and the Uptimize CRM (system of record). Each sink is isolated: a thrown
// error in one must never stop the others (see `deliverLead`'s
// Promise.allSettled fan-out), and none may ever throw back into the
// webhook handler -- `deliverLead` always resolves.
//
// Global constraint: `call_type === "message"` calls (vendors, partners,
// anyone who just wants Jonathan to know they called) go to Telegram ONLY --
// they must never enter the leads funnel (Netlify form -> sales agent's
// daily check) or the CRM as a lead.
//
// Global constraint: `brain === "openai-lab"` leads are a test/lab route --
// they skip Netlify and the CRM entirely (no point polluting the real
// pipeline or the CRM with lab traffic) but still ping Telegram, tagged
// 🧪 LAB, so a human can see the lab route is alive.
import type { Lead } from "./contract";
import type { Env } from "./index";

export interface DeliveryResult {
  netlify: boolean;
  telegram: boolean;
  crm: boolean;
}

// -- Netlify --------------------------------------------------------------

/** Forwards a lead into the `starter-project` Netlify Form as an urlencoded
 * POST, matching the fields the real web form submits. Skips (returns
 * `false`, no request made) for lab leads or when NETLIFY_SITE_URL isn't
 * configured. Throws on a non-ok response -- the caller (`deliverLead`)
 * decides what to do with a failure. */
export async function netlifySink(lead: Lead, env: Env, fetchImpl: typeof fetch): Promise<boolean> {
  if (lead.brain === "openai-lab") return false;
  if (lead.call_type === "message") return false;
  if (!env.NETLIFY_SITE_URL) return false;

  const form = new URLSearchParams({
    "form-name": "starter-project",
    name: lead.name,
    email: lead.email,
    phone: lead.callback_number,
    business: lead.business,
    process: lead.process,
    source: "phone-intake",
  });

  // Netlify runs submissions through Akismet, and a server-to-server POST
  // with no User-Agent and no Referer is a textbook spam signature -- every
  // phone-intake lead through 2026-08-20 landed in the spam queue this way
  // (invisible to the sales agent, no email notification). A browser-like
  // UA plus the on-site form page as Referer makes the submission look like
  // what it semantically is: the starter form being filled on the caller's
  // behalf.
  const res = await fetchImpl(new URL("/", env.NETLIFY_SITE_URL).toString(), {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent":
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
      Referer: new URL("/starter/", env.NETLIFY_SITE_URL).toString(),
    },
    body: form.toString(),
  });
  if (!res.ok) throw new Error(`Netlify sink failed: HTTP ${res.status}`);

  await rescuePhoneIntakeFromSpam(env, fetchImpl);
  return true;
}

/** Netlify runs every form submission through Akismet, and short server-side
 * phone-intake submissions keep getting classified as spam even with
 * browser-like headers (proven live 2026-08-20: the UA/Referer fix passed a
 * synthetic test, then the very next real call landed in the spam queue
 * anyway). Spam-queue submissions are invisible to the sales agent's lead
 * check and send no notification email, so a spammed lead is a lost lead.
 *
 * Every `source=phone-intake` submission is worker-generated by construction
 * -- there is no way for third-party spam to carry that marker through this
 * sink's own POST. So after each successful POST, sweep the form's spam
 * queue and mark every phone-intake entry as ham (which also trains
 * Akismet). Best-effort: requires NETLIFY_API_TOKEN + NETLIFY_FORM_ID, never
 * throws (the submission itself succeeded; rescue is a repair pass), and
 * self-heals older stuck leads on the next call. */
async function rescuePhoneIntakeFromSpam(env: Env, fetchImpl: typeof fetch): Promise<void> {
  if (!env.NETLIFY_API_TOKEN || !env.NETLIFY_FORM_ID) return;

  // Up to 3 attempts: the first sleep also gives Netlify a beat to run the
  // submission through Akismet, and the retries cover transient edge
  // failures -- observed live 2026-08-20: a Workers subrequest to
  // api.netlify.com intermittently dies with Cloudflare error 1042, and a
  // single-shot sweep left that call's lead stranded in spam until the next
  // call's sweep found it. Total worst-case delay (~9s + fetches) stays
  // comfortably inside waitUntil's budget.
  for (let attempt = 1; attempt <= 3; attempt++) {
    await new Promise((resolve) => setTimeout(resolve, 3000));

    try {
      const listRes = await fetchImpl(
        `https://api.netlify.com/api/v1/forms/${env.NETLIFY_FORM_ID}/submissions?state=spam&per_page=20`,
        { headers: { Authorization: `Bearer ${env.NETLIFY_API_TOKEN}` } }
      );
      if (!listRes.ok) {
        console.error(`voice-intake: spam-queue list failed (attempt ${attempt}): HTTP ${listRes.status}`);
        continue;
      }

      const submissions = (await listRes.json()) as Array<{ id: string; data?: { source?: string } }>;
      let allRescued = true;
      for (const submission of submissions) {
        if (submission?.data?.source !== "phone-intake") continue;
        const hamRes = await fetchImpl(`https://api.netlify.com/api/v1/submissions/${submission.id}/ham`, {
          method: "PUT",
          headers: { Authorization: `Bearer ${env.NETLIFY_API_TOKEN}` },
        });
        if (!hamRes.ok) {
          allRescued = false;
          console.error(
            `voice-intake: ham-rescue of ${submission.id} failed (attempt ${attempt}): HTTP ${hamRes.status}`
          );
        }
      }
      if (allRescued) return;
    } catch (err) {
      console.error(`voice-intake: spam-queue rescue failed (attempt ${attempt})`, err);
    }
  }
}

// -- Telegram ---------------------------------------------------------------

function telegramText(lead: Lead): string {
  const prefixes: string[] = [];
  if (lead.call_type === "message") prefixes.push("📝 MESSAGE FOR JONATHAN");
  if (lead.urgent) prefixes.push("🔴 URGENT");
  if (lead.existing_client) prefixes.push("🔴 EXISTING CLIENT");
  if (lead.brain === "openai-lab") prefixes.push("🧪 LAB");
  const header = prefixes.length > 0 ? `${prefixes.join(" — ")}\n` : "";

  if (lead.call_type === "message") {
    return (
      `${header}${lead.summary || "(no summary)"}\n\n` +
      `Name: ${lead.name || "(not given)"}\n` +
      `Company: ${lead.business || "(not given)"}\n` +
      `Message: ${lead.message || "(none left)"}\n` +
      `Phone: ${lead.callback_number || "(not given)"}\n` +
      `Email: ${lead.email || "(not given)"}\n\n` +
      `Transcript: ${lead.transcript_url}`
    );
  }

  return (
    `${header}${lead.summary || "(no summary)"}\n\n` +
    `Name: ${lead.name || "(not given)"}\n` +
    `Business: ${lead.business || "(not given)"}\n` +
    `Process: ${lead.process || "(not given)"}\n` +
    `Phone: ${lead.callback_number || "(not given)"}\n` +
    `Email: ${lead.email || "(not given)"}\n\n` +
    `Transcript: ${lead.transcript_url}`
  );
}

async function sendTelegramMessage(env: Env, fetchImpl: typeof fetch, text: string): Promise<Response> {
  return fetchImpl(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chat_id: env.TELEGRAM_CHAT_ID, text }),
  });
}

/** Pings the Telegram channel with the lead's details. Not lab-fenced --
 * lab leads still ping, tagged 🧪 LAB, so the route is visibly alive. Skips
 * (returns `false`, no request made) when TELEGRAM_BOT_TOKEN/CHAT_ID aren't
 * configured. Throws on a non-ok response. */
export async function telegramSink(lead: Lead, env: Env, fetchImpl: typeof fetch): Promise<boolean> {
  if (!env.TELEGRAM_BOT_TOKEN || !env.TELEGRAM_CHAT_ID) return false;

  const res = await sendTelegramMessage(env, fetchImpl, telegramText(lead));
  if (!res.ok) throw new Error(`Telegram sink failed: HTTP ${res.status}`);
  return true;
}

// -- CRM ----------------------------------------------------------------

// The CRM requires an Origin matching its CSRF allowlist on every request
// plus the CF Access service-token headers, even for server-to-server
// calls (ported from lanefit/worker/src/crm.ts, where a hardcoded origin
// caused real login 403s). Derived from CRM_BASE_URL so re-pointing the
// worker can't silently desync the two.
//
// Route prefix (confirmed live, Task 4): the CRM's Nest app mounts its
// controllers at the root (`/auth/login`, `/leads`), but the public edge is
// an nginx reverse proxy that only forwards the `/api/` location -- it
// strips that prefix before proxying to the app
// (`crm-web`'s default.conf: `location /api/ { proxy_pass http://api:3000/; }`).
// Everything outside `/api/` falls through to nginx's static SPA
// `try_files`, which 405s on POST. So externally the routes are
// `/api/auth/login` and `/api/leads`, not the bare root paths.
const CRM_API_PREFIX = "/api";

function crmHeaders(env: Env, extra?: Record<string, string>): Record<string, string> {
  return {
    Origin: new URL(env.CRM_BASE_URL as string).origin,
    "CF-Access-Client-Id": env.CF_ACCESS_CLIENT_ID ?? "",
    "CF-Access-Client-Secret": env.CF_ACCESS_CLIENT_SECRET ?? "",
    ...extra,
  };
}

/** Logs into the CRM and carries forward every `Set-Cookie` the response
 * sent (session cookie, and -- since the request also crosses Cloudflare
 * Access -- Access's own `CF_Authorization` cookie). `Headers#get("set-cookie")`
 * collapses multiple Set-Cookie headers into one lossy string; `getSetCookie()`
 * (confirmed live, Task 4: the CRM's login sets two) is the only correct way
 * to read them all. The CRM's AuthGuard only ever reads its own session
 * cookie, but there's no reason not to forward Access's too. There's no JSON
 * bearer token -- the real login response is just `{ ok: true }`. */
async function crmLogin(env: Env, fetchImpl: typeof fetch): Promise<string | undefined> {
  const res = await fetchImpl(`${env.CRM_BASE_URL}${CRM_API_PREFIX}/auth/login`, {
    method: "POST",
    headers: crmHeaders(env, { "Content-Type": "application/json" }),
    body: JSON.stringify({ email: env.CRM_EMAIL, password: env.CRM_PASSWORD }),
  });
  if (!res.ok) throw new Error(`CRM login failed: HTTP ${res.status}`);

  const cookies = res.headers.getSetCookie();
  if (cookies.length === 0) return undefined;
  return cookies.map((c) => c.split(";")[0]).join("; ");
}

/** Logs in, then creates a CRM lead. Skips (returns `false`, no request
 * made) for lab leads or when CRM_BASE_URL/CRM_EMAIL/CRM_PASSWORD aren't
 * configured. Throws on any non-ok response.
 *
 * Payload shape confirmed live against the CRM's `createLeadSchema`
 * (Task 4): it's a Zod `.strict()` object accepting only `name`, `email`,
 * `phone`, `company`, `sourceId` (an existing lead_source UUID, optional),
 * and `notes` -- extra keys (a `title`, a free-text `source` string) 400 with
 * "Unrecognized key(s)". There's no title field, so the "Phone intake --"
 * framing that used to be the lead's title is now the first line of notes
 * instead. */
export async function crmSink(lead: Lead, env: Env, fetchImpl: typeof fetch): Promise<boolean> {
  if (lead.brain === "openai-lab") return false;
  if (lead.call_type === "message") return false;
  if (!env.CRM_BASE_URL || !env.CRM_EMAIL || !env.CRM_PASSWORD) return false;

  const cookie = await crmLogin(env, fetchImpl);
  const authHeaders: Record<string, string> = {};
  if (cookie) authHeaders.Cookie = cookie;

  const notes = [
    `Phone intake — ${lead.name || lead.callback_number}`,
    lead.summary,
    lead.process,
    lead.transcript_url,
  ]
    .filter(Boolean)
    .join("\n\n");
  const res = await fetchImpl(`${env.CRM_BASE_URL}${CRM_API_PREFIX}/leads`, {
    method: "POST",
    headers: crmHeaders(env, { "Content-Type": "application/json", ...authHeaders }),
    body: JSON.stringify({
      name: lead.name || lead.callback_number,
      email: lead.email || undefined,
      phone: lead.callback_number,
      company: lead.business || undefined,
      notes,
      ...(env.CRM_LEAD_SOURCE_ID ? { sourceId: env.CRM_LEAD_SOURCE_ID } : {}),
    }),
  });
  if (!res.ok) throw new Error(`CRM lead create failed: HTTP ${res.status}`);
  return true;
}

// -- Fan-out ----------------------------------------------------------

function errorPingText(lead: Lead, failedSinks: string[]): string {
  return (
    `⚠️ Lead delivery sink failure: ${failedSinks.join(", ")}\n` +
    `Caller: ${lead.name || lead.callback_number}\n` +
    `Check the Worker logs -- the lead may not have reached every sink.`
  );
}

/** Fans a parsed lead out to all three sinks in isolation: one sink's
 * throw never stops the others (Promise.allSettled), and this function
 * itself never throws -- it's always safe to hand to `ctx.waitUntil`.
 * On any sink failure it sends one extra Telegram error ping, unless
 * Telegram itself was the sink that failed (then there's no channel to
 * ping through, so it just logs). */
export async function deliverLead(
  lead: Lead,
  env: Env,
  fetchImpl: typeof fetch = fetch
): Promise<DeliveryResult> {
  const [netlifyOutcome, telegramOutcome, crmOutcome] = await Promise.allSettled([
    netlifySink(lead, env, fetchImpl),
    telegramSink(lead, env, fetchImpl),
    crmSink(lead, env, fetchImpl),
  ]);

  const failedSinks: string[] = [];
  for (const [name, outcome] of [
    ["netlify", netlifyOutcome],
    ["telegram", telegramOutcome],
    ["crm", crmOutcome],
  ] as const) {
    if (outcome.status === "rejected") {
      failedSinks.push(name);
      console.error(`voice-intake: ${name} sink failed`, outcome.reason);
    }
  }

  if (failedSinks.length > 0) {
    if (telegramOutcome.status === "rejected") {
      // Telegram is the failed sink itself -- no channel left to ping
      // through. Already logged above.
    } else {
      try {
        const res = await sendTelegramMessage(env, fetchImpl, errorPingText(lead, failedSinks));
        if (!res.ok) {
          console.error(`voice-intake: error ping to Telegram failed: HTTP ${res.status}`);
        }
      } catch (err) {
        console.error("voice-intake: error ping to Telegram failed", err);
      }
    }
  }

  return {
    netlify: netlifyOutcome.status === "fulfilled" ? netlifyOutcome.value : false,
    telegram: telegramOutcome.status === "fulfilled" ? telegramOutcome.value : false,
    crm: crmOutcome.status === "fulfilled" ? crmOutcome.value : false,
  };
}
